title: 盛春 
email: shengchun@shujia.io
description: > # this means to ignore newlines until "baseurl:"
  chunzi
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chunzi.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
markdown: kramdown
theme: jekyll-theme-minimal
